FROM node:18-alpine
WORKDIR /usr/app
COPY package.json ./
RUN npm install
COPY tsconfig.json ./
COPY src src
COPY test test
COPY test/files/blankpdf.pdf /files/storage/d7/31/d520ca21a90b2ca28b5068cfdd678dbd3ace
COPY test/files/bobcat.jpg /files/storage/6c/e1/19a866c6821764edcdd5b30395d0997c8aff
CMD [ "npm", "run", "mocha", "--silent" ]
