services:
  dosgato-test:
    build:
      context: test
    environment:
      MYSQL_USER: dosgato # might not need these environment variables. Does test need to connect to DB?
      MYSQL_PASS: password
      MYSQL_DATABASE: dosgatotest
      MYSQL_HOST: mysql
      JWT_SECRET: secret
    depends_on:
      mysql:
        condition: service_healthy
      dosgato-api:
        condition: service_started
  dosgato-api:
    build:
      context: .
    environment:
      NODE_ENV: development
      MYSQL_USER: dosgato
      MYSQL_PASS: password
      MYSQL_DATABASE: dosgatotest
      MYSQL_HOST: mysql
      JWT_SECRET: secret
      SKIP_BOOTSTRAP: 'true'
      RESET_DB_ON_STARTUP: 'true'
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: percona/percona-server:8.4
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dosgatotest
      MYSQL_USER: dosgato
      MYSQL_PASSWORD: password
    volumes:
      - dosgatotestdb:/var/lib/mysql
    healthcheck:
      #test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 6
volumes:
  dosgatotestdb: {}
