version: '3'
services:
  dosgato-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      MYSQL_USER: dosgato
      MYSQL_PASS: password
      MYSQL_DATABASE: dosgatotest
      MYSQL_HOST: mysql
    depends_on:
      - mysql
  mysql:
    image: percona:5
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dosgatotest
      MYSQL_USER: dosgato
      MYSQL_PASSWORD: password
    volumes:
      - dosgatotestdb:/var/lib/mysql
volumes:
  dosgatotestdb: {}
