version: '3'
services:
  dosgato:
    build:
      context: .
    environment:
      MYSQL_USER: dosgato
      MYSQL_PASS: password
      MYSQL_DATABASE: dosgatotest
      MYSQL_HOST: mariadb
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dosgatotest
      MYSQL_USER: dosgato
      MYSQL_PASSWORD: password
