version: '3'
services:
  dosgato:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 9229:9229
    environment:
      NODE_ENV: development
      MYSQL_USER: dosgato
      MYSQL_PASS: password
      MYSQL_DATABASE: dosgatodev
      MYSQL_HOST: mysql
      RESET_DB_ON_STARTUP: 'false'
      JWT_SECRET: secret
    volumes:
      - ./src:/usr/app/src
      - ./testserver:/usr/app/testserver
      - ./test/files/blankpdf.pdf:/files/storage/d7/31/d520ca21a90b2ca28b5068cfdd678dbd3ace
      - ./test/files/bobcat.jpg:/files/storage/6c/e1/19a866c6821764edcdd5b30395d0997c8aff
    depends_on:
      - mysql
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dosgatodev
      MYSQL_USER: dosgato
      MYSQL_PASSWORD: password
    volumes:
      - dosgatodb:/var/lib/mysql
volumes:
  dosgatodb: {}
